### ISSUE TITLE
add testsets based on correspondence patterns

### ISSUE THREAD

**Issue by LinguList** [PhyloStar/MSA#7]
I have this new (and secret) algorithm for inferring correspondence patterns. It basically imputes missing data and reduces the number of columns in all alignments of a dataset, as it just takes the best ones. I think this would be a perfect case for you to apply your algos, right? As you don't have to compute all similar columns, where all is "p p p p p f", but I'd give you the informative ones.

**Comment by PhyloStar** [comment]
@LinguList already is doing a different repo. We can wait.
